[package]
name = "win-clipboard"
version = "1.0.0"
authors = ["Sindre Sorhus <sindresorhus@gmail.com>", "Vsevolod Strukchinsky <floatdrop@gmail.com>"]

[dependencies]
clap = "~2.33.1"
clipboard-win = "2.0.1"
encoding = "0.2"
regex = "1"
